import { useMemo, useState } from 'react'
import { Bell, Bookmark, BrainCircuit, ChevronDown, ChevronLeft, CircleUserRound, Clock3, Database, ExternalLink, History, Home, Menu, Microscope, Network, Search, Settings, ShieldCheck, Sparkles, Wifi, X, Zap } from 'lucide-react'
import './index.css'

type Technology = { id:number; title:string; english:string; year:number; category:string; status:'فعال'|'در حال توسعه'; summary:string; origin:string; impact:string; icon:typeof Wifi; color:string; soft:string; border:string; milestones:{year:string;title:string;text:string}[] }

const technologies: Technology[] = [
  { id:1,title:'اینترنت',english:'Internet',year:1969,category:'ارتباطات',status:'فعال',summary:'شبکه‌ای جهانی که شیوه ارتباط، دسترسی به اطلاعات و اقتصاد را برای همیشه تغییر داد.',origin:'ایالات متحده، پروژه آرپانت',impact:'زیرساخت اصلی ارتباطات و خدمات دیجیتال جهان',icon:Wifi,color:'#2563eb',soft:'#eff6ff',border:'#bfdbfe',milestones:[{year:'۱۹۶۹',title:'تولد آرپانت',text:'نخستین پیام میان دو رایانه دانشگاهی ارسال شد.'},{year:'۱۹۸۳',title:'استاندارد TCP/IP',text:'شبکه‌ها با یک زبان مشترک به هم متصل شدند.'},{year:'۱۹۹۱',title:'وب جهان‌گستر',text:'تیم برنرز لی وب را در دسترس عموم قرار داد.'},{year:'امروز',title:'شبکه‌ای برای همه‌چیز',text:'میلیاردها انسان و دستگاه به اینترنت متصل‌اند.'}]},
  { id:2,title:'هوش مصنوعی',english:'Artificial Intelligence',year:1956,category:'نرم‌افزار',status:'در حال توسعه',summary:'دانشی برای ساخت سامانه‌هایی که یاد می‌گیرند، استدلال می‌کنند و مسائل پیچیده را حل می‌کنند.',origin:'ایالات متحده، کنفرانس دارتموث',impact:'تحول در سلامت، صنعت، آموزش و تولید محتوا',icon:BrainCircuit,color:'#7c3aed',soft:'#f5f3ff',border:'#ddd6fe',milestones:[{year:'۱۹۵۶',title:'کنفرانس دارتموث',text:'اصطلاح هوش مصنوعی به‌طور رسمی مطرح شد.'},{year:'۱۹۹۷',title:'پیروزی دیپ‌بلو',text:'رایانه IBM قهرمان شطرنج جهان را شکست داد.'},{year:'۲۰۱۲',title:'انقلاب یادگیری عمیق',text:'شبکه‌های عصبی جهشی بزرگ در تشخیص تصویر رقم زدند.'},{year:'امروز',title:'هوش مصنوعی مولد',text:'مدل‌ها متن، تصویر، ویدئو و کد تولید می‌کنند.'}]},
  { id:3,title:'رایانش کوانتومی',english:'Quantum Computing',year:1981,category:'سخت‌افزار',status:'در حال توسعه',summary:'رویکردی نو به محاسبات با استفاده از ویژگی‌های فیزیک کوانتوم برای حل مسائل بسیار دشوار.',origin:'ایالات متحده، ایده ریچارد فاینمن',impact:'افق تازه برای رمزنگاری، داروسازی و شبیه‌سازی',icon:Network,color:'#0891b2',soft:'#ecfeff',border:'#a5f3fc',milestones:[{year:'۱۹۸۱',title:'ایده محاسبه کوانتومی',text:'فاینمن پیشنهاد شبیه‌سازی طبیعت با رایانه کوانتومی را داد.'},{year:'۱۹۹۴',title:'الگوریتم شور',text:'برتری نظری رایانش کوانتومی نشان داده شد.'},{year:'۲۰۱۹',title:'برتری کوانتومی',text:'گوگل انجام یک محاسبه ویژه را گزارش کرد.'},{year:'امروز',title:'عصر NISQ',text:'رقابت برای ساخت سامانه‌های پایدار و مقیاس‌پذیر ادامه دارد.'}]},
  { id:4,title:'بلاک‌چین',english:'Blockchain',year:2008,category:'نرم‌افزار',status:'فعال',summary:'دفترکل توزیع‌شده‌ای که ثبت شفاف و تغییرناپذیر تراکنش‌ها را بدون نهاد مرکزی ممکن می‌کند.',origin:'شبکه جهانی، مقاله ساتوشی ناکاموتو',impact:'دارایی دیجیتال، قرارداد هوشمند و خدمات غیرمتمرکز',icon:Database,color:'#ea580c',soft:'#fff7ed',border:'#fed7aa',milestones:[{year:'۲۰۰۸',title:'انتشار مقاله بیت‌کوین',text:'طرح یک پول الکترونیکی همتا‌به‌همتا منتشر شد.'},{year:'۲۰۰۹',title:'بلوک پیدایش',text:'اولین بلوک شبکه بیت‌کوین استخراج شد.'},{year:'۲۰۱۵',title:'قراردادهای هوشمند',text:'اتریوم برنامه‌پذیری را به بلاک‌چین آورد.'},{year:'امروز',title:'زیرساخت غیرمتمرکز',text:'کاربردها از مالی تا هویت دیجیتال گسترش یافته‌اند.'}]},
  { id:5,title:'زیست‌فناوری',english:'Biotechnology',year:1973,category:'علوم زیستی',status:'فعال',summary:'به‌کارگیری سامانه‌های زنده برای توسعه درمان‌ها، محصولات کشاورزی و فرایندهای صنعتی نوین.',origin:'ایالات متحده، DNA نوترکیب',impact:'درمان ژنتیکی، واکسن و کشاورزی دقیق',icon:Microscope,color:'#16a34a',soft:'#f0fdf4',border:'#bbf7d0',milestones:[{year:'۱۹۷۳',title:'DNA نوترکیب',text:'نخستین انتقال موفق ژن میان موجودات انجام شد.'},{year:'۲۰۰۳',title:'ژنوم انسان',text:'نقشه پایه ژنتیکی انسان تکمیل شد.'},{year:'۲۰۱۲',title:'ویرایش CRISPR',text:'ویرایش دقیق و ساده‌تر ژن‌ها ممکن شد.'},{year:'امروز',title:'پزشکی شخصی',text:'درمان‌ها متناسب با ویژگی‌های ژنتیکی طراحی می‌شوند.'}]},
  { id:6,title:'واقعیت مجازی',english:'Virtual Reality',year:1968,category:'رابط کاربری',status:'فعال',summary:'محیط‌های تعاملی و شبیه‌سازی‌شده‌ای که تجربه حضور در جهانی دیجیتال را ایجاد می‌کنند.',origin:'ایالات متحده، شمشیر داموکلس',impact:'بازی، آموزش، طراحی و همکاری از راه دور',icon:Sparkles,color:'#db2777',soft:'#fdf2f8',border:'#fbcfe8',milestones:[{year:'۱۹۶۸',title:'نخستین هدست',text:'نمونه اولیه نمایشگر نصب‌شده روی سر ساخته شد.'},{year:'۱۹۹۱',title:'آرکیدهای واقعیت مجازی',text:'تجربه‌های عمومی و تجاری اولیه شکل گرفت.'},{year:'۲۰۱۶',title:'نسل مصرفی',text:'هدست‌های مدرن وارد بازار عمومی شدند.'},{year:'امروز',title:'رایانش فضایی',text:'مرز میان واقعیت مجازی و افزوده کم‌رنگ‌تر شده است.'}]},
]
const categories=['همه دسته‌ها','ارتباطات','نرم‌افزار','سخت‌افزار','علوم زیستی','رابط کاربری']
const navItems=[{label:'خانه',icon:Home},{label:'فناوری‌ها',icon:Zap},{label:'تاریخچه فناوری',icon:History,active:true},{label:'نشان‌شده‌ها',icon:Bookmark}]

function App(){
  const [search,setSearch]=useState(''); const [category,setCategory]=useState('همه دسته‌ها'); const [sort,setSort]=useState('قدیمی‌ترین'); const [selected,setSelected]=useState<Technology|null>(null); const [bookmarks,setBookmarks]=useState<number[]>([]); const [mobileMenu,setMobileMenu]=useState(false)
  const filtered=useMemo(()=>{const list=technologies.filter(t=>(category==='همه دسته‌ها'||t.category===category)&&`${t.title} ${t.english} ${t.summary}`.toLowerCase().includes(search.toLowerCase()));return [...list].sort((a,b)=>sort==='جدیدترین'?b.year-a.year:a.year-b.year)},[search,category,sort])
  const toggleBookmark=(id:number)=>setBookmarks(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id])
  return <div className="min-h-screen bg-[#f7f8fb] text-[#182033]" dir="rtl">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center gap-8 px-5 lg:px-10">
      <button className="lg:hidden" onClick={()=>setMobileMenu(true)} aria-label="باز کردن منو"><Menu/></button><a href="#history" className="flex items-center gap-2.5"><span className="grid size-10 place-items-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-200"><Zap size={21} fill="currentColor"/></span><span className="text-xl font-black">فناوران</span></a>
      <nav className="hidden h-full items-center gap-1 lg:flex">{navItems.map(item=><a key={item.label} href="#history" className={`nav-link ${item.active?'active':''}`}><item.icon size={18}/>{item.label}</a>)}</nav>
      <div className="mr-auto flex items-center gap-2"><button className="icon-btn" aria-label="اعلان‌ها"><Bell size={20}/><span className="absolute left-2 top-2 size-2 rounded-full border-2 border-white bg-red-500"/></button><button className="icon-btn hidden sm:grid" aria-label="تنظیمات"><Settings size={20}/></button><div className="mr-2 hidden items-center gap-2 border-r border-slate-200 pr-4 sm:flex"><CircleUserRound className="text-slate-500"/><span className="text-sm font-bold">مهمان</span><ChevronDown size={15}/></div></div>
    </div></header>
    {mobileMenu&&<div className="fixed inset-0 z-50 bg-slate-950/30 lg:hidden" onClick={()=>setMobileMenu(false)}><aside className="h-full w-72 bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-8 flex items-center justify-between"><b className="text-xl">فناوران</b><button onClick={()=>setMobileMenu(false)}><X/></button></div>{navItems.map(item=><a key={item.label} href="#history" onClick={()=>setMobileMenu(false)} className={`nav-link mb-2 ${item.active?'active':''}`}><item.icon size={19}/>{item.label}</a>)}</aside></div>}
    <main id="history" className="mx-auto max-w-[1280px] px-5 py-10 lg:px-8 lg:py-14">
      <section className="mb-9 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-sm font-bold text-blue-600"><History size={17}/>دانشنامه سیر تحول فناوری</div><h1 className="mb-3 text-3xl font-black tracking-tight sm:text-4xl">تاریخچه فناوری</h1><p className="max-w-2xl leading-8 text-slate-500">از نخستین جرقه یک ایده تا جایگاه امروز آن؛ مسیر شکل‌گیری، نقاط عطف، دسته‌بندی و وضعیت کنونی فناوری‌ها را کاوش کنید.</p></div><div className="flex gap-3"><div className="stat"><strong>{technologies.length}</strong><span>فناوری</span></div><div className="stat"><strong>۵</strong><span>دسته‌بندی</span></div><div className="stat"><strong>۶۸+</strong><span>سال تاریخ</span></div></div></section>
      <section className="mb-8 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} className="field w-full pr-12" placeholder="جست‌وجو در نام یا توضیحات فناوری..."/></label><label className="select-wrap"><span>دسته‌بندی</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={16}/></label><label className="select-wrap"><span>مرتب‌سازی</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>قدیمی‌ترین</option><option>جدیدترین</option></select><ChevronDown size={16}/></label></div></section>
      <div className="mb-5 flex items-center justify-between"><h2 className="font-extrabold">نمایش {filtered.length} فناوری</h2><span className="hidden text-xs text-slate-400 sm:block">برای مشاهده جزئیات، یک فناوری را انتخاب کنید</span></div>
      {filtered.length?<section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((tech,index)=><article key={tech.id} className="tech-card" style={{animationDelay:`${index*65}ms`}}><div className="mb-5 flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl" style={{background:tech.soft,color:tech.color,border:`1px solid ${tech.border}`}}><tech.icon size={24}/></span><div><h3 className="text-lg font-black">{tech.title}</h3><p className="mt-1 text-xs text-slate-400" dir="ltr">{tech.english}</p></div></div><button onClick={()=>toggleBookmark(tech.id)} className={`bookmark ${bookmarks.includes(tech.id)?'saved':''}`}><Bookmark size={18} fill={bookmarks.includes(tech.id)?'currentColor':'none'}/></button></div><p className="min-h-[76px] text-sm leading-7 text-slate-500">{tech.summary}</p><div className="my-5 flex flex-wrap gap-2"><span className="chip"><Clock3 size={13}/>آغاز: {tech.year}</span><span className="chip">{tech.category}</span><span className={`chip status ${tech.status==='فعال'?'live':'progress'}`}><i/>{tech.status}</span></div><div className="flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">{tech.milestones.length} نقطه عطف</span><button onClick={()=>setSelected(tech)} className="details">مشاهده تاریخچه <ChevronLeft size={17}/></button></div></article>)}</section>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center"><Search className="mx-auto mb-3 text-slate-300" size={40}/><h3 className="font-bold">فناوری‌ای پیدا نشد</h3><button className="mt-3 text-sm text-blue-600" onClick={()=>{setSearch('');setCategory('همه دسته‌ها')}}>پاک کردن فیلترها</button></div>}
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1280px] flex-col items-center justify-between gap-3 px-6 py-7 text-xs text-slate-400 sm:flex-row"><span>© ۱۴۰۴ فناوران — روایت تحول فناوری</span><div className="flex gap-5"><a href="#history">درباره پروژه</a><a href="#history">منابع</a><a href="#history">ارتباط با ما</a></div></div></footer>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="absolute left-5 top-5 grid size-9 place-items-center rounded-full bg-slate-100 text-slate-500" onClick={()=>setSelected(null)}><X size={19}/></button><div className="flex items-center gap-4 border-b border-slate-100 p-6 sm:p-8"><span className="grid size-14 place-items-center rounded-2xl" style={{background:selected.soft,color:selected.color}}><selected.icon size={28}/></span><div><div className="mb-1 flex items-center gap-2"><h2 className="text-2xl font-black">{selected.title}</h2><span className={`chip status ${selected.status==='فعال'?'live':'progress'}`}><i/>{selected.status}</span></div><p className="text-sm text-slate-400" dir="ltr">{selected.english}</p></div></div><div className="max-h-[72vh] overflow-y-auto p-6 sm:p-8"><p className="mb-6 leading-8 text-slate-600">{selected.summary}</p><div className="mb-8 grid grid-cols-1 gap-3 sm:grid-cols-3"><Info icon={Clock3} label="سال شکل‌گیری" value={String(selected.year)}/><Info icon={ShieldCheck} label="دسته‌بندی" value={selected.category}/><Info icon={ExternalLink} label="خاستگاه" value={selected.origin}/></div><div className="mb-7 rounded-xl bg-blue-50 p-4"><b className="mb-1 block text-sm text-blue-800">اثرگذاری امروز</b><p className="text-sm leading-7 text-blue-700">{selected.impact}</p></div><h3 className="mb-6 font-black">خط زمانی رویدادها</h3><div className="timeline">{selected.milestones.map((m,i)=><div className="timeline-item" key={m.year}><span className="dot" style={{background:selected.color}}/><div className="mb-1 flex items-center gap-3"><b>{m.title}</b><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500">{m.year}</span></div><p className="text-sm leading-7 text-slate-500">{m.text}</p>{i<selected.milestones.length-1&&<span className="line"/>}</div>)}</div></div></div></div>}
  </div>
}
function Info({icon:Icon,label,value}:{icon:typeof Clock3;label:string;value:string}){return <div className="rounded-xl border border-slate-200 p-3"><div className="mb-1 flex items-center gap-1.5 text-[11px] text-slate-400"><Icon size={13}/>{label}</div><b className="text-sm">{value}</b></div>}
export default App
